name: CI

on:
  pull_request:
    branches: [ Master, develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: xcodebuild -project 'PetSafeCodeChallengeUIKit.xcodeproj' -scheme 'PetSafeCodeChallengeUIKit' -destination 'platform=iOS Simulator,name=iPhone 11' test

      # Runs a set of commands using the runners shell
      - name: Build App
        run: xcodebuild -project 'PetSafeCodeChallengeUIKit.xcodeproj' -scheme 'PetSafeCodeChallengeUIKit' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
        
